//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceShopApp.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_a_import21
    {
        public int ID { get; set; }
        public string Наименование_товара { get; set; }
        public decimal Цена { get; set; }
        public string Описание { get; set; }
        public string Главное_изображение { get; set; }
        public bool Активен { get; set; }
        public Nullable<int> ID_manufacturer { get; set; }
    }
}
