//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceShopApp.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsale_a_import12
    {
        public int ID { get; set; }
        public System.DateTime Дата_и_время_продажи { get; set; }
        public int Товар { get; set; }
        public int Количество { get; set; }
        public Nullable<int> ClientService_id { get; set; }
    }
}
